name: Isici.Core.Abstractions Build

on:
  push:
    branches: [ master ]
    paths: src/Isici.Core.Abstractions
  pull_request:
    branches: [ master ]
    paths: src/Isici.Core.Abstractions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --project src/Isici.Core.Abstractions/Isici.Core.Abstractions.csproj --configuration Release --no-restore
