name: Isici Core CI
on:
  pull_request:
    branches: [ master ]
    paths: 'src/Isici.Core/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Isici.Core/Isici.Core.csproj  --configuration Release 
